# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 16:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('mail', models.CharField(max_length=64)),
                ('userid', models.CharField(max_length=64)),
                ('uuid', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Baseline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64, unique=True)),
                ('bid', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=512)),
                ('comment', models.CharField(default='', max_length=1024)),
                ('created', models.CharField(default='', max_length=64)),
                ('createtime', models.DateTimeField(blank=True, default=None, null=True)),
                ('historys_processed', models.BooleanField(default=False)),
                ('migrated', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BaselineInStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historys_processed', models.BooleanField(default=False)),
                ('migrated', models.BooleanField(default=False)),
                ('out_verify', models.TextField(default='')),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtc.Baseline')),
            ],
            options={
                'ordering': ('stream', '-baseline'),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64)),
                ('sequence', models.IntegerField(default=1)),
                ('comment', models.TextField(default='')),
                ('migrated', models.BooleanField(default=False)),
                ('compared', models.BooleanField(default=False)),
                ('compressed', models.BooleanField(default=False)),
                ('showstopper', models.BooleanField(default=False)),
                ('created', models.CharField(default='', max_length=64)),
                ('createtime', models.DateTimeField(blank=True, default=None, null=True)),
                ('delivered', models.CharField(default='', max_length=64)),
                ('delivertime', models.DateTimeField(blank=True, default=None, null=True)),
                ('out_resume', models.TextField(default='')),
                ('out_load', models.TextField(default='')),
                ('out_verify', models.TextField(default='')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rtc.Author')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rtc.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('category', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='rtc.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pathhint', models.CharField(default='', max_length=128)),
                ('typeoutgoing', models.CharField(default='', max_length=32)),
                ('typeproposed', models.CharField(default='', max_length=32)),
                ('json', models.TextField(default='')),
                ('changesets', models.ManyToManyField(to='rtc.ChangeSet')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GitBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('branchpoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rtc.ChangeSet')),
            ],
        ),
        migrations.CreateModel(
            name='GitCommit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitid', models.CharField(default='commitid', max_length=128, unique=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('out_status', models.TextField(default='')),
                ('out_add', models.TextField(default='')),
                ('out_commit', models.TextField(default='')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='JsonRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=255, unique=True)),
                ('output', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('uuid', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(default='', max_length=256)),
                ('comment', models.CharField(default='', max_length=1024)),
                ('created', models.CharField(default='', max_length=64)),
                ('createtime', models.DateTimeField(blank=True, default=None, null=True)),
                ('changesets_listed', models.BooleanField(default=False)),
                ('changesets_compared', models.BooleanField(default=False)),
                ('migrated', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('baselines', models.ManyToManyField(to='rtc.Baseline')),
                ('lastchangeset', mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rtc.ChangeSet')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='rtc.Snapshot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('uuid', models.CharField(max_length=64, unique=True)),
                ('history_updated', models.BooleanField(default=False)),
                ('history_partial', models.BooleanField(default=False)),
                ('history_inconsistent', models.BooleanField(default=False)),
                ('changesets_compared', models.BooleanField(default=False)),
                ('migrated', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('baselines', models.ManyToManyField(to='rtc.Baseline')),
                ('category', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='rtc.Category')),
                ('component', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forstreams', to='rtc.Component')),
                ('components', models.ManyToManyField(blank=True, default=None, related_name='instreams', to='rtc.Component')),
                ('firstchangeset', mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firstchangesets', to='rtc.ChangeSet')),
                ('historys', models.ManyToManyField(blank=True, related_name='instreams', to='rtc.ChangeSet')),
                ('historys_inconsistent', models.ManyToManyField(blank=True, default=None, related_name='historyinconsistentstreams', to='rtc.Component')),
                ('historys_partial', models.ManyToManyField(blank=True, default=None, related_name='historypartialstreams', to='rtc.Component')),
                ('historys_updated', models.ManyToManyField(blank=True, default=None, related_name='historyupdatedstreams', to='rtc.Component')),
                ('lastchangeset', mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lastchangesets', to='rtc.ChangeSet')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='rtc.Stream')),
                ('project', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtc.ProjectArea')),
                ('snapshots', models.ManyToManyField(to='rtc.Snapshot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('label', models.TextField(default='')),
                ('uuid', models.CharField(max_length=64, unique=True)),
                ('displayed', models.BooleanField(default=False, editable=False)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='rtc.Workitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkitemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('uuid', models.CharField(default='', max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('baseline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rtc.Baseline')),
                ('component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rtc.Component')),
                ('snapshot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rtc.Snapshot')),
                ('stream', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rtc.Stream')),
            ],
        ),
        migrations.AddField(
            model_name='workitem',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rtc.WorkitemType'),
        ),
        migrations.AddField(
            model_name='changeset',
            name='commit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rtc.GitCommit'),
        ),
        migrations.AddField(
            model_name='changeset',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rtc.ChangeSet', verbose_name='following'),
        ),
        migrations.AddField(
            model_name='changeset',
            name='workitems',
            field=models.ManyToManyField(to='rtc.Workitem'),
        ),
        migrations.AddField(
            model_name='baselineinstream',
            name='firstchangeset',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firstchangeset', to='rtc.ChangeSet'),
        ),
        migrations.AddField(
            model_name='baselineinstream',
            name='historys',
            field=models.ManyToManyField(blank=True, related_name='changesethistory', to='rtc.ChangeSet'),
        ),
        migrations.AddField(
            model_name='baselineinstream',
            name='lastchangeset',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lastchangeset', to='rtc.ChangeSet'),
        ),
        migrations.AddField(
            model_name='baselineinstream',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtc.Stream'),
        ),
        migrations.AddField(
            model_name='baseline',
            name='category',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='rtc.Category'),
        ),
        migrations.AddField(
            model_name='baseline',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtc.Component'),
        ),
        migrations.AddField(
            model_name='baseline',
            name='contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rtc.Contributor'),
        ),
        migrations.AddField(
            model_name='baseline',
            name='historys',
            field=models.ManyToManyField(blank=True, to='rtc.ChangeSet'),
        ),
        migrations.AddField(
            model_name='baseline',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='rtc.Baseline'),
        ),
        migrations.AlterUniqueTogether(
            name='changeset',
            unique_together=set([('uuid', 'sequence')]),
        ),
        migrations.AlterUniqueTogether(
            name='baselineinstream',
            unique_together=set([('baseline', 'stream')]),
        ),
    ]
