# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtc', '0002_stream_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseline',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='baselineinstream',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
