# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 16:31
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rtc', '0003_auto_20170124_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseline',
            name='lastchangeset',
            field=mptt.fields.TreeForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baselines_lastchangeset_set', to='rtc.ChangeSet'),
        ),
    ]
