# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtc', '0004_baseline_lastchangeset'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
