# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtc', '0005_stream_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseline',
            name='tagged',
            field=models.BooleanField(default=False),
        ),
    ]
