# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtc', '0006_baseline_tagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseline',
            name='tagname',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
