# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtc', '0007_baseline_tagname'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='pushed',
            field=models.BooleanField(default=False),
        ),
    ]
